### ISSUE TITLE
feat: add pipeline

### ISSUE THREAD

**Issue by VaibhavUpreti** [shivesh-ranjan/gooze#1]
lmao
![avo](https://user-images.githubusercontent.com/85568177/201920907-d57fb4ff-a5ee-4391-b7fa-d8bd47e76a95.png)

**Comment by shivesh-ranjan** [comment]
![image](https://user-images.githubusercontent.com/86239697/201924847-22618d7f-1f78-494c-852d-4b9e26c07d7f.png)
